// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using orchid_backend_net.Infrastructure.Persistence;

#nullable disable

namespace orchid_backend_net.Infrastructure.Migrations
{
    [DbContext(typeof(OrchidDbContext))]
    [Migration("20260315182257_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.AnalyticResults", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<decimal>("Anthracnose")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BacterialWilt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Blackrot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Brownspots")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Healthy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MoldBacterial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MoldFungus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Oxidation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoftRot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StemRot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Virus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WitheredYellowRoot")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("AnalyticResults");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Batches", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BatchSizeHeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BatchSizeWidth")
                        .HasColumnType("numeric");

                    b.Property<string>("HeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WidthUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("LabRoomId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Characteristic", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Chemicals", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcentrationUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Chemicals");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Config", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Disease", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.DiseaseIncident", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<decimal>("AIConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MonitoringLogId")
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("SampleStageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("MonitoringLogId");

                    b.HasIndex("SampleStageId");

                    b.ToTable("DiseaseIncidents");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.ExperimentLogs", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("ExpectedSampleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Issues")
                        .HasColumnType("text");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text");

                    b.Property<string>("SeedlingParentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("BatchId");

                    b.HasIndex("MethodId");

                    b.HasIndex("SeedlingParentId");

                    b.ToTable("ExperimentLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Imgs", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsNewest")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Imgs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LabRooms", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("LabRooms");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LogDetails", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MeasuredValue")
                        .HasColumnType("numeric");

                    b.Property<string>("MonitoringLogsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StageRequirementDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MonitoringLogsId");

                    b.HasIndex("StageRequirementDefinitionId");

                    b.ToTable("MonitoringLogDetails");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Materials", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MethodStageDefinition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MethodStageDefinition");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MethodStages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DurationsDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSampleGenerated")
                        .HasColumnType("boolean");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<int>("MethodStageDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MethodId");

                    b.HasIndex("MethodStageDefinitionId");

                    b.ToTable("MethodStages");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Methods", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MonitoringLogs", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("AnalyticResultId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNewest")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("SampleStageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AnalyticResultId")
                        .IsUnique();

                    b.HasIndex("DiseaseId");

                    b.HasIndex("SampleStageId");

                    b.HasIndex("UserId");

                    b.ToTable("MonitoringLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SafeProcedure", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcedureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("SafeProcedures");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SafeProcedureStep", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SafeProcedureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SafeProcedureStepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SafeProcedureId");

                    b.ToTable("SafeProcedureStep");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SampleStage", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SampleStageDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartedAt")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SampleId");

                    b.HasIndex("SampleStageDefinitionId");

                    b.ToTable("SampleStages");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SampleStageDefinition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxDurationDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("SampleStageDefinition");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Samples", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExecutionDate")
                        .HasColumnType("date");

                    b.Property<string>("ExperimentLogId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitialCondition")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ExperimentLogId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SamplesRequirementsDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("SamplesRequirementDefinitions");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Seedlings", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentAId")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ParentAId");

                    b.ToTable("Seedlings");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SeedlingsTraits", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeedlingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("SeedlingId");

                    b.ToTable("SeedlingsTraits");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageChemicals", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("ChemicalId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ChemicalId");

                    b.HasIndex("StageId");

                    b.ToTable("StageChemicals");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageMaterials", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MaterialId");

                    b.HasIndex("StageId");

                    b.ToTable("StageMaterials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageRequirementDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<decimal>("ExpectedValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("SampleRequirementDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SampleStageDefinitionId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SampleRequirementDefinitionId");

                    b.HasIndex("SampleStageDefinitionId");

                    b.ToTable("StageRequirementDefinitions");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.HasIndex("TechnicianId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAttributes", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int?>("ChemicalId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("ChemicalId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAttributes");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskCheckList", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("TaskChecks");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskCheckListItem", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Evaluated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExpectedMaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExpectedMinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("ExpectedUnit")
                        .HasColumnType("text");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("boolean");

                    b.Property<string>("MeasurementUnit")
                        .HasColumnType("text");

                    b.Property<decimal?>("MesuredValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskCheckListId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("TaskCheckListId");

                    b.ToTable("TaskCheckListItems");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Tasks", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearcherId")
                        .HasColumnType("text");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Users", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Batches", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.LabRooms", "LabRoom")
                        .WithMany("Batches")
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRoom");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.DiseaseIncident", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Disease", "Disease")
                        .WithMany()
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.MonitoringLogs", "MonitoringLog")
                        .WithMany()
                        .HasForeignKey("MonitoringLogId");

                    b.HasOne("orchid_backend_net.Domain.Entities.SampleStage", "SampleStage")
                        .WithMany()
                        .HasForeignKey("SampleStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("MonitoringLog");

                    b.Navigation("SampleStage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.ExperimentLogs", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Batches", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Methods", "Method")
                        .WithMany("ExperimentLogs")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "SeedlingParent")
                        .WithMany("ExperimentLogs")
                        .HasForeignKey("SeedlingParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Method");

                    b.Navigation("SeedlingParent");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LogDetails", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.MonitoringLogs", "MonitoringLogs")
                        .WithMany("LogDetails")
                        .HasForeignKey("MonitoringLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.StageRequirementDefinition", "StageRequirementDefinition")
                        .WithMany()
                        .HasForeignKey("StageRequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringLogs");

                    b.Navigation("StageRequirementDefinition");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MethodStages", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Methods", "Method")
                        .WithMany("MethodStages")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.MethodStageDefinition", "MethodStageDefinition")
                        .WithMany()
                        .HasForeignKey("MethodStageDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("MethodStageDefinition");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MonitoringLogs", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.AnalyticResults", "AnalyticResult")
                        .WithOne("MonitoringLog")
                        .HasForeignKey("orchid_backend_net.Domain.Entities.MonitoringLogs", "AnalyticResultId");

                    b.HasOne("orchid_backend_net.Domain.Entities.Disease", "Disease")
                        .WithMany("MonitoringLogs")
                        .HasForeignKey("DiseaseId");

                    b.HasOne("orchid_backend_net.Domain.Entities.SampleStage", "SampleStage")
                        .WithMany("MonitoringLogs")
                        .HasForeignKey("SampleStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Users", "User")
                        .WithMany("MonitoringLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalyticResult");

                    b.Navigation("Disease");

                    b.Navigation("SampleStage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SafeProcedureStep", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.SafeProcedure", "SafeProcedure")
                        .WithMany("SafeProcedureSteps")
                        .HasForeignKey("SafeProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SafeProcedure");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SampleStage", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Samples", "Samples")
                        .WithMany("SampleStages")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.SampleStageDefinition", "SampleStageDefinition")
                        .WithMany()
                        .HasForeignKey("SampleStageDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleStageDefinition");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Samples", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.ExperimentLogs", "ExperimentLog")
                        .WithMany("Samples")
                        .HasForeignKey("ExperimentLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentLog");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Seedlings", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "ParentA")
                        .WithMany()
                        .HasForeignKey("ParentAId");

                    b.Navigation("ParentA");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SeedlingsTraits", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Characteristic", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "Seedling")
                        .WithMany("SeedlingsTraits")
                        .HasForeignKey("SeedlingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristics");

                    b.Navigation("Seedling");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageChemicals", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Chemicals", "Chemical")
                        .WithMany("StageChemicals")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.MethodStages", "MethodStage")
                        .WithMany("StageChemicals")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("MethodStage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageMaterials", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Materials", "Material")
                        .WithMany("StageMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.MethodStages", "MethodStage")
                        .WithMany("StageMaterials")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MethodStage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageRequirementDefinition", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.SamplesRequirementsDefinition", "SampleRequirementsDefinition")
                        .WithMany()
                        .HasForeignKey("SampleRequirementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.SampleStageDefinition", "SampleStage")
                        .WithMany("StageRequirementDefinitions")
                        .HasForeignKey("SampleStageDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleRequirementsDefinition");

                    b.Navigation("SampleStage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAssignment", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Tasks", "Task")
                        .WithOne("TaskAssignment")
                        .HasForeignKey("orchid_backend_net.Domain.Entities.TaskAssignment", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Users", "Technician")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAttributes", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Chemicals", "Chemicals")
                        .WithMany()
                        .HasForeignKey("ChemicalId");

                    b.HasOne("orchid_backend_net.Domain.Entities.Materials", "Materials")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("orchid_backend_net.Domain.Entities.Tasks", "Tasks")
                        .WithMany("TaskAttributes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemicals");

                    b.Navigation("Materials");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskCheckList", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Tasks", "Task")
                        .WithOne("CheckList")
                        .HasForeignKey("orchid_backend_net.Domain.Entities.TaskCheckList", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskCheckListItem", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.TaskCheckList", "TaskCheckList")
                        .WithMany("Items")
                        .HasForeignKey("TaskCheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskCheckList");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Users", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.AnalyticResults", b =>
                {
                    b.Navigation("MonitoringLog")
                        .IsRequired();
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Chemicals", b =>
                {
                    b.Navigation("StageChemicals");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Disease", b =>
                {
                    b.Navigation("MonitoringLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.ExperimentLogs", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LabRooms", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Materials", b =>
                {
                    b.Navigation("StageMaterials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MethodStages", b =>
                {
                    b.Navigation("StageChemicals");

                    b.Navigation("StageMaterials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Methods", b =>
                {
                    b.Navigation("ExperimentLogs");

                    b.Navigation("MethodStages");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MonitoringLogs", b =>
                {
                    b.Navigation("LogDetails");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SafeProcedure", b =>
                {
                    b.Navigation("SafeProcedureSteps");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SampleStage", b =>
                {
                    b.Navigation("MonitoringLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SampleStageDefinition", b =>
                {
                    b.Navigation("StageRequirementDefinitions");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Samples", b =>
                {
                    b.Navigation("SampleStages");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Seedlings", b =>
                {
                    b.Navigation("ExperimentLogs");

                    b.Navigation("SeedlingsTraits");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskCheckList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Tasks", b =>
                {
                    b.Navigation("CheckList");

                    b.Navigation("TaskAssignment")
                        .IsRequired();

                    b.Navigation("TaskAttributes");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Users", b =>
                {
                    b.Navigation("MonitoringLogs");

                    b.Navigation("TaskAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
