// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using orchid_backend_net.Infrastructure.Persistence;

#nullable disable

namespace orchid_backend_net.Infrastructure.Migrations
{
    [DbContext(typeof(OrchidDbContext))]
    partial class OrchidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.AnalyticResults", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<decimal>("Anthracnose")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BacterialWilt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Blackrot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Brownspots")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Healthy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MoldBacterial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MoldFungus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Oxidation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoftRot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StemRot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Virus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WitheredYellowRoot")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("AnalyticResults");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Batches", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<int>("LabRoomId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("LabRoomId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Characteristic", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Chemicals", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcentrationUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Chemicals");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.ExperimentLogs", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("HybridzationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HybridzationsID")
                        .HasColumnType("text");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BatchId");

                    b.HasIndex("HybridzationsID");

                    b.HasIndex("MethodId");

                    b.ToTable("ExperimentLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Hybridzations", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("ParentAId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentBId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ParentAId");

                    b.HasIndex("ParentBId");

                    b.ToTable("Hybridzations");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Imgs", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("MonitoringLogsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MonitoringLogsId");

                    b.ToTable("Imgs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LabRooms", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("LabRooms");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LogDetails", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MeasuredValue")
                        .HasColumnType("numeric");

                    b.Property<string>("MonitoringLogsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MonitoringLogsId");

                    b.HasIndex("RequirementId");

                    b.ToTable("MonitoringLogDetails");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Materials", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Catetgory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Methods", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationsDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MonitoringLogs", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("AnalyticResultId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SampleStageOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("UpdatedDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AnalyticResultId")
                        .IsUnique();

                    b.HasIndex("SampleId");

                    b.HasIndex("UserId");

                    b.ToTable("MonitoringLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Roles", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Samples", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExecutionDate")
                        .HasColumnType("date");

                    b.Property<string>("ExperimentLogId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ExperimentLogId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SamplesRequirements", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("ExpectedValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("StageId");

                    b.ToTable("SamplesRequirements");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Seedlings", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentAId")
                        .HasColumnType("text");

                    b.Property<string>("ParentBId")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ParentAId");

                    b.HasIndex("ParentBId");

                    b.ToTable("Seedlings");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SeedlingsTraits", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeedlingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("SeedlingId");

                    b.ToTable("SeedlingsTraits");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageChemicals", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("ChemicalId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ChemicalId");

                    b.HasIndex("StageId");

                    b.ToTable("StageChemicals");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageMaterials", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MaterialId");

                    b.HasIndex("StageId");

                    b.ToTable("StageMaterials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Stages", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MethodId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("SampleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("SampleId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAttributes", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("ChemicalId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("ChemicalId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAttributes");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Tasks", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearcherId")
                        .HasColumnType("text");

                    b.Property<string>("StageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Users", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Batches", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.LabRooms", "LabRoom")
                        .WithMany("Batches")
                        .HasForeignKey("LabRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRoom");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.ExperimentLogs", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Batches", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Hybridzations", "Hybridzations")
                        .WithMany()
                        .HasForeignKey("HybridzationsID");

                    b.HasOne("orchid_backend_net.Domain.Entities.Methods", "Method")
                        .WithMany("ExperimentLogs")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Hybridzations");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Hybridzations", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "ParentA")
                        .WithMany()
                        .HasForeignKey("ParentAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "ParentB")
                        .WithMany()
                        .HasForeignKey("ParentBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentA");

                    b.Navigation("ParentB");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Imgs", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.MonitoringLogs", "MonitoringLogs")
                        .WithMany()
                        .HasForeignKey("MonitoringLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringLogs");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LogDetails", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.MonitoringLogs", "MonitoringLogs")
                        .WithMany("LogDetails")
                        .HasForeignKey("MonitoringLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.SamplesRequirements", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringLogs");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MonitoringLogs", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.AnalyticResults", "AnalyticResult")
                        .WithOne("MonitoringLog")
                        .HasForeignKey("orchid_backend_net.Domain.Entities.MonitoringLogs", "AnalyticResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Samples", "Sample")
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Users", "User")
                        .WithMany("MonitoringLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalyticResult");

                    b.Navigation("Sample");

                    b.Navigation("User");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Samples", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.ExperimentLogs", "ExperimentLog")
                        .WithMany("Samples")
                        .HasForeignKey("ExperimentLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentLog");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SamplesRequirements", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Stages", "Stage")
                        .WithMany("SamplesRequirements")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Seedlings", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "ParentA")
                        .WithMany()
                        .HasForeignKey("ParentAId");

                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "ParentB")
                        .WithMany()
                        .HasForeignKey("ParentBId");

                    b.Navigation("ParentA");

                    b.Navigation("ParentB");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.SeedlingsTraits", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Characteristic", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Seedlings", "Seedling")
                        .WithMany("SeedlingsTraits")
                        .HasForeignKey("SeedlingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristics");

                    b.Navigation("Seedling");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageChemicals", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Chemicals", "Chemical")
                        .WithMany("StageChemicals")
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Stages", "Stage")
                        .WithMany("StageChemicals")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemical");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.StageMaterials", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Materials", "Material")
                        .WithMany("StageMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Stages", "Stage")
                        .WithMany("StageMaterials")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Stages", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Methods", "Method")
                        .WithMany("Stages")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAssignment", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Samples", "Sample")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Tasks", "Task")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Users", "Technician")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sample");

                    b.Navigation("Task");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.TaskAttributes", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Chemicals", "Chemicals")
                        .WithMany()
                        .HasForeignKey("ChemicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Materials", "Materials")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("orchid_backend_net.Domain.Entities.Tasks", "Tasks")
                        .WithMany("TaskAttributes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chemicals");

                    b.Navigation("Materials");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Users", b =>
                {
                    b.HasOne("orchid_backend_net.Domain.Entities.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.AnalyticResults", b =>
                {
                    b.Navigation("MonitoringLog")
                        .IsRequired();
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Chemicals", b =>
                {
                    b.Navigation("StageChemicals");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.ExperimentLogs", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.LabRooms", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Materials", b =>
                {
                    b.Navigation("StageMaterials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Methods", b =>
                {
                    b.Navigation("ExperimentLogs");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.MonitoringLogs", b =>
                {
                    b.Navigation("LogDetails");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Samples", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Seedlings", b =>
                {
                    b.Navigation("SeedlingsTraits");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Stages", b =>
                {
                    b.Navigation("SamplesRequirements");

                    b.Navigation("StageChemicals");

                    b.Navigation("StageMaterials");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Tasks", b =>
                {
                    b.Navigation("TaskAssignments");

                    b.Navigation("TaskAttributes");
                });

            modelBuilder.Entity("orchid_backend_net.Domain.Entities.Users", b =>
                {
                    b.Navigation("MonitoringLogs");

                    b.Navigation("TaskAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
